# Generated by Django 4.0.5 on 2022-07-03 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='image',
        ),
        migrations.AddField(
            model_name='post',
            name='image_url',
            field=models.URLField(null=True, verbose_name='image url'),
        ),
        migrations.AlterField(
            model_name='post',
            name='created_on',
            field=models.DateField(auto_now_add=True, verbose_name='time created'),
        ),
        migrations.AlterField(
            model_name='post',
            name='edited_on',
            field=models.DateField(auto_now=True, verbose_name='time edited'),
        ),
        migrations.AlterField(
            model_name='post',
            name='text',
            field=models.TextField(verbose_name='url of the post image'),
        ),
        migrations.AlterField(
            model_name='post',
            name='title',
            field=models.CharField(max_length=250, verbose_name='title of the post'),
        ),
    ]
