name: "build pipeline for beta release"

on:
  pull_request:
    branches:
      - main

jobs:
  build:
    name: build and release
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-java@v1
        with:
          java-version: '12.x'
      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
      - run: flutter pub get
      - run: flutter test
      - run: flutter build appbundle
      # setup fastlane beta release
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: '2.7.2'
      - uses: maierj/fastlane-action@v2.2.0
        with:
          lane: 'beta'
          subdirectory: 'android'