name: "build pipeline for beta release"

on: 
  push:
    branches:
    - web-main
    
  pull_request:
    branches:
    - web-main

jobs:
  build:
    name: build and release
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-java@v1
        with:
          java-version: '12.x'
